### ISSUE TITLE
PostCSS Conversion Checklist

### ISSUE THREAD

**Issue by shellscape** [lesshint/lesshint#158]
Starting this issue to track progress on the conversion to using PostCSS.

Misc Tasks:
- [x] merge linting fixes from master
- [x] merge changes from #156, when that is merged 
- [x] util module for common operations. see note on then/catch with the parser below.
- [x] write proper value parser
- [x] move to postcss-values-parser

Linters:
- [x] attributeQuotes
- [x] borderZero
- [x] comment
- [x] decimalZero
- [x] depthLevel
- [x] duplicateProperty
- [x] emptyRule
- [x] finalNewline
- [x] hexLength
- [x] hexNotation
- [x] hexValidation
- [x] idSelector
- [x] importantRule
- [x] importPath
- [x] propertyOrdering
- [x] propertyUnits
- [x] qualifyingElement
- [x] selectorNaming
- [x] singleLinePerProperty
- [x] singleLinePerSelector
- [x] spaceAfterPropertyColon
- [x] spaceAfterPropertyName
- [x] spaceAfterPropertyValue
- [x] spaceAroundComma
- [x] spaceAroundOperator
- [x] spaceBeforeBrace
- [x] spaceBetweenParens
- [x] stringQuotes
- [x] trailingSemicolon
- [x] trailingWhitespace
- [x] urlFormat
- [x] urlQuotes
- [x] zeroUnit

**Then/Catch**

Considering the following code:

```js
parser = getParser(source);
parser.then(function (ast) {
  expect(linter.nodeTypes).to.include(ast.root.first.type);
});
```
If that expect throws an AssertionError, it's swallowed by the Promise implementation of PostCSS less. So we'll essentially get a false-positive for the expect result. Found this while implementing new tests for the `nodeTypes` property in the comments linter. ~~And so we need to have a `.catch(...)` for every parse operation.~~ And so we need to return the promise for every `it()`. We already have a ton of copy/paste'd code in the specs, so a small util lib that wraps this for us is reasonable.

**Comment by shellscape** [comment]
Just pushed the attributeQuotes linter and specs to the postcss branch. It took some doing, and I had to add another third party postcss module; postcss-selector-parser. It works very well, although does strip some metadata I'd expect to be there. I'm tracking that in https://github.com/postcss/postcss-selector-parser/issues/50.

I'm liking the AST setup of PostCSS a lot more than gonzales-pe overall. From what I've read in the issues on the PostCSS project's repo, they're working on integrating the attribute parsing - but as little as we're using it, I think having to use another parser is OK for now.

fwiw, I'm backpedaling on the idea of sticking with the gilt postcss-less project over webschik's. Decision was a bit too reactionary, and I think the project will be responsive and well-maintained by webschik.

**Comment by shellscape** [comment]
@jwilsson any chance you can tackle the two merges on the list today? For some reason my git-fu is failing and I can't get a clean merge to this branch from master.

**Comment by shellscape** [comment]
Knocked out 12 of the parsers. Will have some more free time towards the weekend.

**Comment by shellscape** [comment]
So postcss doesn't parse values by default (same with the selectors). While postcss-selector-parser is relatively mature, postcss-value-parser is not when compared to the two other projects. I'm using it in a few linters; https://github.com/TrySound/postcss-value-parser. Things like walking the different segments of a Declaration value are missing, and we're approaching a point where we're going to have a lot of copy/pasted code to enable walking the parsed value tree.

@jwilsson I'd like to fork postcss-value-parser to the lesshint account, and start working on improvements to bring it more in line with postcss and postcss-selector-parser. (I don't have permissions to do that) Overall that'll save us time and reduce the complexity of many of the linters.

**Comment by jwilsson** [comment]
@shellscape Great job!

You should be able to create repositories now.

**Comment by shellscape** [comment]
@jwilsson cool. I've got the value parser coding portion done, and I'm working on unit tests now that match postcss-value-parser (minus some really weird rules he was allowing, like unmatched parens and quotes).

let's get you and @kokarn to knock out a few of those remaining linters that don't rely on property parsing ;)

**Comment by shellscape** [comment]
@jwilsson @kokarn I've completed work on the first version of my value parser for postcss. it's under the Lesshint org here; https://github.com/lesshint/postcss-values-parser

**Comment by jwilsson** [comment]
@shellscape Awesome work! 

I'll try to squeeze some work in later this week.

**Comment by shellscape** [comment]
@jwilsson great :)

Keep an eye on postcss-less. There some...  interesting things going on there. It may be my next target afterall.

**Comment by shellscape** [comment]
Got the values parser updated to postcss-values-parser and it's working great!

**Comment by shellscape** [comment]
only a few more to do @jwilsson @kokarn :)

**Comment by jwilsson** [comment]
`spaceAroundComma` just needs the fix in https://github.com/lesshint/postcss-values-parser/pull/3 and then everything is finished! 😄 

I do think we need some sort of helper to ensure the reported columns are correct, I think we've got some issues there right now.

**Comment by shellscape** [comment]
🎉  I merged and published a new version with that fix.

**Comment by jwilsson** [comment]
And we're finished! 😃  🎉 

We just got some weird test failures on `attributeQuotes` (it doesn't seem to load the parser correctly) and as I mentioned earlier, the columns (and possibly lines) are probably not correctly reported in all cases. I think we're ignoring the indentation in some cases for example.

**Comment by jwilsson** [comment]
Alright, I managed to solve the failing `attributeQuotes` tests. It was because we were running Mocha on the test `utils.js` file and that somehow messed it up.

**Comment by shellscape** [comment]
👍 shall we close this one?
