### ISSUE TITLE
2.0 master todo list

### ISSUE THREAD

**Issue by jwilsson** [lesshint/lesshint#168]
Just a short list of the things I think we should include in `2.0` :tada: 

- [x] PostCSS Conversion (#158)
- [x] Remove old reporter usage support
- [x] Possible zeroUnit behavior change (#165)
- [x] Move stylish reporter to its own package (#147)

Did I miss anything?

**Comment by jwilsson** [comment]
Now that #158 is finished we're really close to a final `2.0`! 🎉 

Two things that I've been thinking about:
* We're still supporting Node `0.10` which doesn't support Promises, PostCSS suggets adding a Promise polyfill which looks like it will just add a global Promise object (https://github.com/postcss/postcss/#nodejs-010-and-the-promise-api). I don't think we should do that, perhaps we should just drop `0.10` support? It's in maintenance mode anyway.
* Would it make sense to release a `2.0-rc`? Just to get some help with catching regressions etc.

**Comment by kokarn** [comment]
+1 for dropping 0.10 and releasing a 2.0.0-rc1

**Comment by wareczek** [comment]
waiting for 2.0-rc :+1:

**Comment by shellscape** [comment]
👍  we should definitely drop 0.10 and I'd be in favor of 0.12 as well.

regarding regressions, we've got a lot of reports of old gonzales failing less that we should probably try to pluck from issues and plop into general "does this fail?" tests. I don't mind the rc tagged release either.

**Comment by shellscape** [comment]
also, I commented on https://github.com/lesshint/lesshint/commit/e2b0cb7cb6ced20b5acd289d180594ae5e033fce. I'm not entirely on board with forcing that to promises because 1. it removes the synchronous nature of lesshint, and 2. it doesn't appear solve an async problem. Promises are all the rage right now, but they shouldn't be added where there isn't an async problem to solve.

**Comment by jwilsson** [comment]
Sure, I'm fine with dropping `0.12` too.

Perhaps we should report parsing related issues at https://github.com/webschik/postcss-less and we'll pick up the fixes from there?

@shellscape I was trying to solve an async problem with it but if you have a better idea, please revert it and add another solution :)

**Comment by shellscape** [comment]
@jwilsson i must be having one of those days... I didn't see where the async issue was. can you point that out for me?

**Comment by shellscape** [comment]
@jwilsson ping re: previous comment. and where do we stand on a 2.0 rc?

**Comment by jwilsson** [comment]
@shellscape My bad, I didn't read the documentations close enough. It was possible to make it synchronous and now it is. 

I discovered that `stringQuotes` doesn't check attribute selectors, I should have time to fix it today and then we should be able to tag an RC.

**Comment by jwilsson** [comment]
The `stringQuotes` issue is fixed and a PR for the PostCSS rewrite is up at #176.

I think we can tag a RC and finish the last things in #165 in the mean time.

**Comment by shellscape** [comment]
@jwilsson anything that we can help with to help this along?

**Comment by jwilsson** [comment]
@shellscape Just too much to do on my end, I'll tag a RC now though.

**Comment by jwilsson** [comment]
`2.0.0-rc` is tagged on npm as `next`, install with `npm install lesshint@next`.

**Comment by shellscape** [comment]
@jwilsson awesome. no worries, figured you were busy. had some time today to help if it was needed.

**Comment by shellscape** [comment]
🎉
