### ISSUE TITLE
Lesshint 1.0

### ISSUE THREAD

**Issue by jwilsson** [lesshint/lesshint#67]
With the [recent changes in grunt-lesshint](https://github.com/lesshint/grunt-lesshint/commit/5c7c6ecd6d7829fe864f4ea569c17b8064c13b06) and our changes with the [Linter refactoring (#56)](https://github.com/lesshint/lesshint/issues/56) I think the time has come to start preparing for a `1.0` release.

Not only will other tools such as [grunt-lesshint](https://github.com/lesshint/grunt-lesshint) and [gulp-lesshint](https://github.com/lesshint/gulp-lesshint) have an easier time (since each minor will simply be fetched automatically) we're also introducing some possible breaking changes in #56 which we should handle gracefully by bumping the major version.

I'm thinking we'd use this issue as a "meta" issue, tracking all changes we'd like to include in the `1.0` release.

- [x] Linter refactoring, tracked in #56.
- [x] Sorting Results by Line Number, tracked in #58.
- [x] Catch errors, i.e. better handling of fatal errors. Tracked in #62.
- [x] ~~Add ability to disable linting for a single line (something we could do once #56 is resolved). Tracked in #55.~~ Postponed until a later release.
- [x] Remove quote style option from attributeQuotes. Tracked in #65.
- [x] Merge spaceAfterComma and spaceBeforeComma. Tracked in #66.
- [x] Wait for gonzales-pe 3.0. Tracked in #78 and [gonzales-pe #94](https://github.com/tonyganch/gonzales-pe/issues/94).

Finalise these defaults
- [x] #10 trailingSemicolon
- [x] #11 emptyRule
- [x] #24 comment
- [x] #26 trailingZero
- [x] #27 zeroUnit
- [x] #30 qualifyingElement
- [x] #36 propertyUnits

I'll create a new `0.x` branch off current `master` in case we need to release bug fixes before `1.0` lands.

Pinging some known users to get some opinions: @kokarn @shellscape @CITguy @srogers202.

**Comment by kokarn** [comment]
:+1: Looks good. 
As long as work is ongoing and not stopping i don't see any issues with this. 

I would propose a deadline tho because most of these things could be updated with a minor or even patch after 1.* is released.

**Comment by shellscape** [comment]
Agreeing with @kokarn - We could pick a subset of those and update with minors. Though I'm not entirely sure that's a major concern. I've got company backing to poke at this stuff at least one day a week, so I can continue fairly regular contributions. (And I'd like to say btw, that I'm grateful for how receptive you all have been to them)

I think that represents a fine milestone roadmap for 1.0, and we should tag it as such. :+1:

**Comment by kokarn** [comment]
Wow, that's incredible. 
We use it where I work as well and I try to poke at when I find something it but haven't got official support for it so it's not as much i'm afraid.

You are a very welcome addition. It's just fun that more people are helping out. Especially since you actually see things that we might've missed or not thought of before.

**Comment by jwilsson** [comment]
Wow, I'm really glad to hear that @shellscape. I've actually been meaning to invite you as a proper collaborator if you're interested?

If we all agree on what we want to do for the release we can try to get everything done as soon as possible and postpone some other non-breaking changes.

I'm thinking we could at least postpone #55 and #62 if necessary.

**Comment by CITguy** [comment]
I'd say that #55 and #56 are really the only two tasks that don't make sense in 1.0 MVP.  Of the remaining tasks, I would say that #62 should be the highest priority given that the hinter isn't doing its job if it skips errors during the parse phase. #65 and #66 will be an API change, so the 0.x to 1.0 leap makes sense in that regard, and default options should be agreed upon and implemented prior to a stable 1.0 release.

Because I'm in the process of setting this up for use with projects at work, some development on the issues mentioned may be workable on the clock. However, this can fluctuate given priorities at work, so I can only truly guarantee development time outside of work (evenings and weekends).

**Comment by kokarn** [comment]
Wow, this is some great news. Glad to see people use this for real-world stuff and not just messing around :dancers:

I agree that #62 is very important and that #65 and #66 should be in 1.0.
We should also go through all the linter options and defaults as that might add some incompatible changes as well.
I've closed the ones which haven't gotten any feedback but if @shellscape and @CITguy would like to check the ones still open and leave some feedback that would be great. 

Currently open: #10 #11 #24 #26 #27 #30 and #36

**Comment by CITguy** [comment]
Sure, I'll take a look tomorrow (Monday 9/14/2015).

**Comment by kokarn** [comment]
Great, thanks!

**Comment by jwilsson** [comment]
I think we should postpone #55, it's not breaking and will keep things moving.

**Comment by kokarn** [comment]
Yeah, let's do that. 1.* would be nice to push :)

**Comment by shellscape** [comment]
I've been occupied by a few crazy weeks on my end. Please proceed with 1.0 how you all think is best. Should be more active in the coming weeks.

**Comment by jwilsson** [comment]
I just closed #27 and a `1.0` tag is coming right up! :tada: 

Thank you for all your hard work guys! Couldn't have done it without you :smile: :+1:

**Comment by CITguy** [comment]
![Woooo!](http://i.imgur.com/ekoBYht.gif)
